### ISSUE TITLE
Failure to build native extensions on Mac OS X 10.8.4

### ISSUE THREAD

**Issue by mtmckenna** [sinisterchipmunk/xmlsec#1]
Hello! Tried to install this gem via Bundler and was unable to build the native extensions. My machine is on Mac OS X 10.8.4. Also, xmlsec1 was installed via Homebrew:

```
$ which xmlsec1
/usr/local/bin/xmlsec1
```

Here's the output from bundler:

```
Installing nokogiri-xmlsec (0.0.4) 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /Users/omada/.rvm/rubies/ruby-2.0.0-p195/bin/ruby extconf.rb 
checking for ruby.h... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/omada/.rvm/rubies/ruby-2.0.0-p195/bin/ruby
    --with-xmlsec1-openssl-config
    --without-xmlsec1-openssl-config
    --with-pkg-config
    --without-pkg-config
extconf.rb:4:in `barf': xmlsec1 is not installed. (RuntimeError)
    from extconf.rb:19:in `<main>'


Gem files will remain installed in /Users/omada/.rvm/gems/ruby-2.0.0-p195@kairos/gems/nokogiri-xmlsec-0.0.4 for inspection.
Results logged to /Users/omada/.rvm/gems/ruby-2.0.0-p195@kairos/gems/nokogiri-xmlsec-0.0.4/ext/nokogiri_ext_xmlsec/gem_make.out

An error occurred while installing nokogiri-xmlsec (0.0.4), and Bundler cannot continue.
Make sure that `gem install nokogiri-xmlsec -v '0.0.4'` succeeds before bundling.
```

Any ideas? Thank you!

**Comment by sinisterchipmunk** [comment]
Luckily I have a mac to reproduce this on :)

Running `pkg-config --exists xmlsec1-openssl --print-errors` displayed a version mismatch relative to `libxml2`.

The steps I took to resolve this were:

```
# [ get or upgrade to the latest version of brew ]

brew install libxml2 libxslt
brew link --force libxml2 libxslt

# [ start new terminal ]

# re-run pkg-config to make sure versions are good
pkg-config --exists xmlsec1-openssl --print-errors
# 0 means no errors
echo $?

# rebuild gems against latest versions
gem install nokogiri
gem install nokogiri-xmlsec
```

This worked for me. Let me know if you have any further issues and I'll reopen this issue.
