### ISSUE TITLE
Bundle install on heroku?

### ISSUE THREAD

**Issue by eccegordo** [sinisterchipmunk/xmlsec#2]
Any thoughts on how to get this to install on heroku easily?

I get the following error. Looks like it can't build `xmlsec1`

I believe heroku is just ubuntu underneath. I read somewhere about copying up Debian packages with source code to resolve the dependencies.

```
       Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

       /tmp/build_8a1504d8-9e0a-4d88-a79e-2d3058767ca8/vendor/ruby-2.0.0/bin/ruby extconf.rb
       checking for ruby.h... yes
       *** extconf.rb failed ***
       Could not create Makefile due to some reason, probably lack of necessary
       libraries and/or headers.  Check the mkmf.log file for more details.  You may
       need configuration options.

       Provided configuration options:
       --with-opt-dir
       --without-opt-dir
       --with-opt-include
       --without-opt-include=${opt-dir}/include
       --with-opt-lib
       --without-opt-lib=${opt-dir}/lib
       --with-make-prog
       --without-make-prog
       --srcdir=.
       --curdir
       --ruby=/tmp/build_8a1504d8-9e0a-4d88-a79e-2d3058767ca8/vendor/ruby-2.0.0/bin/ruby
       --with-xmlsec1-openssl-config
       --without-xmlsec1-openssl-config
       --with-pkg-config
       --without-pkg-config
       extconf.rb:4:in `barf': xmlsec1 is not installed. (RuntimeError)
       from extconf.rb:19:in `<main>'


       Gem files will remain installed in /tmp/build_8a1504d8-9e0a-4d88-a79e-2d3058767ca8/vendor/bundle/ruby/2.0.0/gems/nokogiri-xmlsec-0.0.4 for inspection.
       Results logged to /tmp/build_8a1504d8-9e0a-4d88-a79e-2d3058767ca8/vendor/bundle/ruby/2.0.0/gems/nokogiri-xmlsec-0.0.4/ext/nokogiri_ext_xmlsec/gem_make.out
       An error occurred while installing nokogiri-xmlsec (0.0.4), and Bundler cannot
       continue.
       Make sure that `gem install nokogiri-xmlsec -v '0.0.4'` succeeds before
       bundling.
 !
 !     Failed to install gems via Bundler.
 !

 !     Push rejected, failed to compile Ruby app
```

**Comment by sinisterchipmunk** [comment]
I've never used Heroku. However, you will need to ensure the apt package `libxmlsec1-dev` is installed on ubuntu. You could also try `libxmlsec1-openssl`.
